name: 🥰 反馈问题
description: 一起改进 DDKDN 社区
title: "[Feedback]: "
labels: [feedback]
assignees: 
- 2951121599
body:
- type: markdown
  attributes:
    value: |
      感谢参与到 DDKDN 社区中来，请填写以下信息！
- type: checkboxes
  attributes:
    label: DDKDN 社区中是否已经存在了相似的问题?
    description: 请在 issue 列表中搜索一下社区是否存在类似问题
    options:
    - label: 我已经搜索了现有的issues
      required: true
- type: textarea
  id: field1
  attributes:
    label: 描述
    description: |
      详细描述一下问题
    render: markdown
  validations:
    required: true
- type: textarea
  id: field2
  attributes:
    label: 解决方案
    description: 是否有初步的解决方案
    render: markdown
  validations:
    required: false
- type: textarea
  id: field3
  attributes:
    label: 其他信息?
    description: |
      相关链接或者其他与该问题相关的信息，或者任何其他的背景资料信息
    render: markdown
  validations:
    required: false
